name: pynteractive
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - jupyter
  - voila
  - ipywidgets
  - ipympl
  - ffmpeg
  - pip:
    - requests